version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /packages/eslint-config-godaddy
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /packages/eslint-config-godaddy-flow
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /packages/eslint-config-godaddy-react
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /packages/eslint-config-godaddy-react-flow
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /packages/eslint-config-godaddy-react-typescript
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /packages/eslint-config-godaddy-typescript
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily